name: Package

on:
  [push]

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          submodules: 'true'
        
      - run: echo "Cloning packager..."
      - run: git clone -b "master" "https://github.com/BigWigsMods/packager.git"
      - run: echo "Moving executable..."
      - run: mv packager/release.sh ./
      - run: echo "Deleting packager folder..."
      - run: rm -rf packager
      - run: echo "Settings X bit on executable..."
      - run: chmod +x release.sh

      - name: Package and release
        run: release.sh -g wrath
