name: Package

on:
  push:
    tags:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          submodules: 'true'
        
      - name: Get packager
        run: |
          git clone -b "master" "https://github.com/BigWigsMods/packager.git"
          mv packager/release.sh ./
          rm -rf packager
          chmod +x release.sh

      - name: Package and release
        run: release.sh -g wrath
